// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoxwdltgognzjnlfrrte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhveHdkbHRnb2duempubGZycnRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTM4MDgsImV4cCI6MjA1ODY2OTgwOH0.IGVXEXgOFtc8Yt2PxV3g3-N_6tCQK-xBY9AwVX3f86w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);